//! Evaluator library — attribution metrics and strategy orchestration.

use causpan_core::{GroundTruthEvent, KernelEvent, KernelEventType, MatchKey, OperationKind, RpcId};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Aggregate evaluation results across all strategies.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EvaluationResults {
    pub strategies: Vec<StrategyResults>,
    pub total_kernel_events: usize,
    pub total_ground_truth_events: usize,
    pub matched_events: usize,
    pub unmatched_events: usize,
}

/// Per-strategy results.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyResults {
    pub strategy_name: String,
    pub correct: usize,
    pub wrong_rpc: usize,
    pub unattributed: usize,
    pub precision: f64,
    pub recall: f64,
    pub f1: f64,
    pub wrong_rate: f64,
    pub unattributed_rate: f64,
}

impl StrategyResults {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            strategy_name: name.into(),
            correct: 0,
            wrong_rpc: 0,
            unattributed: 0,
            precision: 0.0,
            recall: 0.0,
            f1: 0.0,
            wrong_rate: 0.0,
            unattributed_rate: 0.0,
        }
    }

    pub fn finalise(&mut self, total_gt: usize, matched: usize) {
        let attributed = self.correct + self.wrong_rpc;
        self.precision = if attributed > 0 {
            self.correct as f64 / attributed as f64
        } else {
            0.0
        };
        self.recall = if total_gt > 0 {
            self.correct as f64 / total_gt as f64
        } else {
            0.0
        };
        self.f1 = if self.precision + self.recall > 0.0 {
            2.0 * self.precision * self.recall / (self.precision + self.recall)
        } else {
            0.0
        };
        self.wrong_rate = if matched > 0 {
            self.wrong_rpc as f64 / matched as f64
        } else {
            0.0
        };
        self.unattributed_rate = if matched > 0 {
            self.unattributed as f64 / matched as f64
        } else {
            0.0
        };
    }
}

// ---------------------------------------------------------------------------
// Matching: align ground-truth and kernel-event streams
// ---------------------------------------------------------------------------

/// A matched pair of a ground-truth event and its corresponding kernel event.
#[derive(Debug, Clone)]
pub struct MatchedPair {
    /// Index in the ground-truth slice.
    pub gt_index: usize,
    /// Index in the kernel-event slice.
    pub ke_index: usize,
    /// The authoritative RPC id (from ground truth).
    pub rpc_id: RpcId,
}

/// Match kernel events to ground-truth events using semantic fingerprints.
///
/// # Approach
///
/// Because the workload is run twice (once for ground truth, once under
/// strace), PID/TID are *not* reliable matching signals.  Instead we:
///
/// 1. Derive a `MatchKey` from each ground-truth event (file path, network
///    target, command string).
/// 2. Derive a `MatchKey` from each kernel event by extracting the path/host
///    from syscall arguments.
/// 3. Group both streams by `MatchKey`.
/// 4. Within each group, align events by timestamp proximity (the strace run
///    is seconds-to-minutes after the ground-truth run, so absolute timestamps
///    won't match — instead we match relative ordering within each group).
///
/// The evaluator then tests attribution strategies on the matched kernel
/// events, comparing each strategy's RPC assignment against the known RPC
/// from the ground-truth pair.
#[derive(Debug)]
pub struct EventMatcher {
    /// Sorted list of matched (gt_index, ke_index, rpc_id) pairs.
    pairs: Vec<MatchedPair>,
    /// Total kernel events (for coverage stats).
    total_kernel_events: usize,
    /// Unmatched kernel event indices (not in any pair).
    unmatched_kernel_indices: Vec<usize>,
}

impl EventMatcher {
    /// Build matches from ground-truth and kernel-event streams.
    ///
    /// Matching algorithm (multi-pass):
    ///
    /// Pass 1 — file operations: match `openat` kernel events to ground-truth
    ///           events by file path (exact string match).
    /// Pass 2 — network operations: match `socket`+`connect` pairs to network
    ///           ground truth.
    /// Pass 3 — process spawn: match `execve` to process_spawn ground truth.
    pub fn new(ground_truth: &[GroundTruthEvent], kernel_events: &[KernelEvent]) -> Self {
        let total_kernel = kernel_events.len();
        let mut pairs: Vec<MatchedPair> = Vec::new();
        let mut matched_ke: Vec<bool> = vec![false; kernel_events.len()];
        let mut matched_gt: Vec<bool> = vec![false; ground_truth.len()];

        // Kernel events that occur before the first ground-truth event are
        // bootstrap/setup syscalls (directory creation, file pre-creation,
        // library loading, etc.) — not operations generated by a logical
        // request.  Exclude them so they cannot steal attribution slots.
        let gt_min_ts = ground_truth
            .iter()
            .map(|e| e.timestamp_ns)
            .min()
            .unwrap_or(0);

        // --- Pass 1: file openat matches ---
        // Group ground-truth file events by path AND operation kind (read vs write).
        let mut gt_file_read: HashMap<String, Vec<(usize, &GroundTruthEvent)>> = HashMap::new();
        let mut gt_file_write: HashMap<String, Vec<(usize, &GroundTruthEvent)>> = HashMap::new();

        for (i, e) in ground_truth.iter().enumerate() {
            if matched_gt[i] { continue; }
            if let causpan_core::OperationTarget::File(f) = &e.target {
                match e.operation {
                    causpan_core::OperationKind::FileRead => {
                        gt_file_read.entry(f.path.clone()).or_default().push((i, e));
                    }
                    causpan_core::OperationKind::FileWrite => {
                        gt_file_write.entry(f.path.clone()).or_default().push((i, e));
                    }
                    _ => {}
                }
            }
        }

        let ke_openat: Vec<(usize, &KernelEvent)> = kernel_events
            .iter()
            .enumerate()
            .filter(|(_, e)| matches!(e.event_type, KernelEventType::Openat))
            .filter(|(_, e)| e.timestamp_ns >= gt_min_ts) // exclude bootstrap/setup
            .filter(|(i, _)| !matched_ke[*i])
            .collect();

        for (ke_idx, ke) in ke_openat {
            let Some(path) = &ke.args.arg1 else { continue };
            let Some(flags_str) = &ke.args.arg2 else { continue };

            // Determine if this openat is a read or write based on flags.
            let is_write = flags_str.contains("O_WRONLY")
                || flags_str.contains("O_RDWR")
                || flags_str.contains("O_CREAT")
                || flags_str.contains("O_TRUNC");
            let is_read = flags_str.contains("O_RDONLY") || flags_str.contains("O_RDWR");

            // Look up the appropriate ground-truth list.
            let gt_list = if is_write && !is_read {
                gt_file_write.get(path.as_str())
            } else if is_read && !is_write {
                gt_file_read.get(path.as_str())
            } else {
                // Ambiguous (e.g. O_RDWR) — try both, prefer the one that has
                // unmatched entries.
                let r = gt_file_read.get(path.as_str());
                let w = gt_file_write.get(path.as_str());
                r.or(w)
            };

            let Some(gt_candidates) = gt_list else { continue };
            for &(gt_idx, gt) in gt_candidates {
                if matched_gt[gt_idx] || matched_ke[ke_idx] {
                    continue;
                }
                pairs.push(MatchedPair {
                    gt_index: gt_idx,
                    ke_index: ke_idx,
                    rpc_id: gt.rpc_id,
                });
                matched_gt[gt_idx] = true;
                matched_ke[ke_idx] = true;
                break;
            }
        }

        // --- Pass 2: network socket/connect ---
        let gt_net: Vec<(usize, &GroundTruthEvent)> = ground_truth
            .iter()
            .enumerate()
            .filter(|(i, _)| !matched_gt[*i])
            .filter(|(_, e)| matches!(e.operation, OperationKind::NetworkConnect))
            .collect();

        let ke_net: Vec<(usize, &KernelEvent)> = kernel_events
            .iter()
            .enumerate()
            .filter(|(i, _)| !matched_ke[*i])
            .filter(|(_, e)| matches!(e.event_type, KernelEventType::Socket | KernelEventType::Connect))
            .collect();

        for (gt_idx, gt) in gt_net {
            if matched_gt[gt_idx] {
                continue;
            }
            for &(ke_idx, ke) in &ke_net {
                if matched_ke[ke_idx] {
                    continue;
                }
                if operation_matches_kernel(gt.operation, ke.event_type) {
                    pairs.push(MatchedPair {
                        gt_index: gt_idx,
                        ke_index: ke_idx,
                        rpc_id: gt.rpc_id,
                    });
                    matched_gt[gt_idx] = true;
                    matched_ke[ke_idx] = true;
                    break;
                }
            }
        }

        // --- Pass 3: process spawn (execve) ---
        let gt_spawn: Vec<(usize, &GroundTruthEvent)> = ground_truth
            .iter()
            .enumerate()
            .filter(|(i, _)| !matched_gt[*i])
            .filter(|(_, e)| matches!(e.operation, OperationKind::ProcessSpawn))
            .collect();

        let ke_exec: Vec<(usize, &KernelEvent)> = kernel_events
            .iter()
            .enumerate()
            .filter(|(i, _)| !matched_ke[*i])
            .filter(|(_, e)| matches!(e.event_type, KernelEventType::Execve))
            .collect();

        for (gt_idx, gt) in gt_spawn {
            if matched_gt[gt_idx] {
                continue;
            }
            for &(ke_idx, ke) in &ke_exec {
                if matched_ke[ke_idx] {
                    continue;
                }
                if operation_matches_kernel(gt.operation, ke.event_type) {
                    pairs.push(MatchedPair {
                        gt_index: gt_idx,
                        ke_index: ke_idx,
                        rpc_id: gt.rpc_id,
                    });
                    matched_gt[gt_idx] = true;
                    matched_ke[ke_idx] = true;
                    break;
                }
            }
        }

        // Collect unmatched kernel event indices.
        let unmatched_kernel_indices: Vec<usize> = (0..total_kernel)
            .filter(|i| !matched_ke[*i])
            .collect();

        Self {
            pairs,
            total_kernel_events: total_kernel,
            unmatched_kernel_indices,
        }
    }

    /// Iterate over matched pairs (ground-truth index, kernel-event index, RPC).
    pub fn pairs(&self) -> &[MatchedPair] {
        &self.pairs
    }

    /// Number of matched kernel events.
    pub fn matched_count(&self) -> usize {
        self.pairs.len()
    }

    /// Number of unmatched kernel events.
    pub fn unmatched_count(&self) -> usize {
        self.unmatched_kernel_indices.len()
    }

    /// Total kernel events seen.
    pub fn total_kernel_events(&self) -> usize {
        self.total_kernel_events
    }
}

/// Does this application-level operation produce the given kernel event type?
fn operation_matches_kernel(op: OperationKind, ev: KernelEventType) -> bool {
    match op {
        OperationKind::FileRead | OperationKind::FileWrite => {
            matches!(ev, KernelEventType::Openat)
        }
        OperationKind::NetworkConnect => {
            matches!(ev, KernelEventType::Socket | KernelEventType::Connect)
        }
        OperationKind::ProcessSpawn => {
            matches!(ev, KernelEventType::Execve)
        }
    }
}
